#!/bin/bash

if [ "$(pgrep -x sway)" ]; then
    source /etc/reglinux/recorder.sway
else
    source /etc/reglinux/recorder.drm
fi

usage() {
    printf "
    Usage: system-record [options]
        --default
        --fast
        --compress
        "
}

ACTION=$1

case "${ACTION}" in
        --fast)
        fast_record
        ;;
        --default)
        default_record
        ;;
        --compress)
        compress_record
        ;;
        -h|--help)
        usage "${0}"
        exit 0
        ;;
        *)
        default_record
        ;;
esac
