#!/bin/bash

if [ "$(pgrep -x sway)" ]; then
    source /etc/reglinux/resolution.sway
else
    source /etc/reglinux/resolution.drm
fi

f_usage() {
    printf "
    Usage: system-resolution [options]
        --listModes
        --listOutputs
        --currentMode
        --currentOutput
        --currentResolution
        --setMode <MODE>
        --setOutput <OUTPUT>
        --setRotation (0|1|2|3)
        --getDisplayMode
        --getRefreshRate
        "
}

if [ $# -eq 0 ]; then
    f_usage
    exit 1
fi

# use for syntax only
PSCREEN=
if test "${1}" = "--screen"
then
    shift
    PSCREEN=$1
    shift
fi

ACTION=$1
shift

case "${ACTION}" in
    "listModes" | "--listModes")
        listModes
    ;;
    "listOutputs" | "--listOutputs")
        listOutputs
    ;;
    "currentMode" | "--currentMode")
        currentMode
    ;;
    "currentOutput" | "--currentOutput")
        currentOutput
    ;;
    "currentResolution" | "--currentResolution")
        currentResolution
    ;;
    "setMode" | "--setMode")
        setMode "$1"
    ;;
    "setOutput" | "--setOutput")
        setOutput "$1"
    ;;
    "setRotation" | "--setRotation")
        setRotation "$1"
    ;;
    "getDisplayMode" | "--getDisplayMode")
        getDisplayMode
    ;;
    "getRefreshRate" | "--getRefreshRate")
        getRefreshRate
    ;;
    "mapTouchScreen" | "--mapTouchScreen")
        mapTouchScreen
    ;;
    "minTomaxResolution" | "minTomaxResolution-secure" | "--minTomaxResolution" | "--minTomaxResolution-secure")
        minTomaxResolution "$1"
    ;;
    "supportSystemRotation" | "--supportSystemRotation")
        supportSystemRotation
    ;;
    *)
        printf "
        error: invalid command ${ACTION}
        "
        f_usage
        exit 1
esac
exit 0
